services:

  eureka-server:
    #image: eureka-server:v1
    build: ../eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  user-service:
    build: .
    container_name: product-service
    ports:
      - "8081:8081"
