server.port=8081

spring.application.name=PRODUCT-SERVICE

#spring.datasource.url=jdbc:postgresql://localhost:5432/Microservices
#spring.datasource.username=postgres
#spring.datasource.password=postgres

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url=${EUREKA_URI}






















#server.port=8081

#spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_WfGnpq7A?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=u_dW9tcT
#spring.datasource.password=DYcqw53ss7Nk

#https://www.freesqldatabase.com/account/
#kufyatorto@necub.com

#spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12835085?useSSL=false&serverTimezone=UTC
#spring.datasource.username=sql12835085
#spring.datasource.password=aNm5I3WErH

#spring.datasource.url=jdbc:postgresql://localhost:5432/Microservices
#spring.datasource.username=postgres
#spring.datasource.password=postgres

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
